import profileImage from "@/assets/profile-image.jpg";

function Home() {
	return (
		<div className="container mx-auto px-4 py-16">
			<div className="flex flex-col md:flex-row items-center justify-center gap-12">
				<div className="md:w-1/3 flex justify-center items-center">
					<div className="relative w-96 h-96">
						<div className="gradient-bg"></div>
						<img
							src={profileImage}
							alt="Sajjad Rafiee"
							className="absolute w-full h-full rounded-full object-cover object-top border-4 border-amber-500/30 
                                    profile-shadow float-animation hover:scale-105 transition-transform duration-300"
						/>
					</div>
				</div>

				<div className="md:w-1/2 text-center md:text-left space-y-6 z-10">
					<h1 className="text-4xl md:text-6xl font-bold gradient-text mb-6">Hello, I'm Elshan</h1>
					<div className="space-y-4 text-gray-700">
						<p className="leading-relaxed">
							I'm a passionate beginner Full Stack Developer with a strong foundation in modern web technologies. My
							journey in web development started with a deep curiosity about how websites work, leading me to
							explore various technologies and frameworks.
						</p>
						<p className="leading-relaxed">
							I specialize in React and Django, creating responsive and user-friendly web applications. My expertise
							includes TypeScript, Tailwind CSS, and modern UI libraries like Framer Motion and Shadcn UI.
						</p>
						<p className="leading-relaxed">
							Through self-learning and hands-on projects, I've developed a solid understanding of both frontend and
							backend development. I'm particularly proud of my projects including a Todo List application, Weather
							App, and a Translator Extension.
						</p>
						<p className="leading-relaxed">
							I'm constantly learning and expanding my skillset, staying up-to-date with the latest web technologies
							and best practices. My goal is to create beautiful, efficient, and user-friendly web applications.
						</p>
						<p className="leading-relaxed">
							When I'm not coding, I enjoy exploring new technologies, contributing to open-source projects, and
							sharing my knowledge with the developer community.
						</p>
						<p className="leading-relaxed">
							I'm currently seeking opportunities to collaborate on exciting projects and continue growing as a
							developer.
						</p>
						<p>Generated by AI</p>
					</div>
					<div className="flex justify-center md:justify-start gap-6 pt-6">
						<a
							href="contact.html"
							className="px-6 py-3 border-2 border-amber-500/50 text-amber-500 rounded-full hover:bg-amber-500/10 
                                  hover:border-amber-400 transform hover:scale-105 transition-all duration-300"
						>
							Get in Touch
						</a>
					</div>
				</div>
			</div>
		</div>
	);
}

export default Home;
